# Generated by Django 2.2.12 on 2020-11-30 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('balance', models.IntegerField()),
                ('password', models.CharField(max_length=86)),
                ('accountNumber', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=43)),
            ],
        ),
    ]
