# Generated by Django 2.2.12 on 2020-12-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='salt',
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=132),
        ),
    ]
