# Generated by Django 2.2.12 on 2020-12-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20201201_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
