# Generated by Django 2.2.12 on 2020-12-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20201201_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
