# Generated by Django 2.2.12 on 2020-12-08 11:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('ammount', models.IntegerField()),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='bank.Account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='bank.Account')),
            ],
        ),
    ]
