# Generated by Django 2.2.12 on 2020-12-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20201211_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='androidID',
            field=models.CharField(default='', max_length=200),
        ),
    ]
